# Generated by Django 4.0.4 on 2023-01-27 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_rename_phone_accountsusermodel_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicleBreakDownModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='vehicleVMainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('descriptionut', models.CharField(max_length=200)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('RUNNING', 'RUNNING'), ('BREAKDOWN', 'BREAKDOWN')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='vehicleInspectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=150)),
                ('break_down', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleInspectionModel_break_down', to='vehicle.vehiclebreakdownmodel')),
            ],
        ),
        migrations.AddField(
            model_name='vehiclebreakdownmodel',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleBreakDownModel_vehicle', to='vehicle.vehiclevmainmodel'),
        ),
        migrations.CreateModel(
            name='vehicleBreakDownImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('status', models.CharField(choices=[('BREAKDOWN', 'BREAKDOWN'), ('INSPECTION', 'INSPECTION')], max_length=120)),
                ('break_down', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleBreakDownImageModel_break_down', to='vehicle.vehiclebreakdownmodel')),
            ],
        ),
        migrations.CreateModel(
            name='vehicleAssignModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assign', 'assign'), ('deassign', 'deassign')], max_length=120)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleAssignModel_owner', to='accounts.accountsusermodel')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleAssignModel_vehicle', to='vehicle.vehiclevmainmodel')),
            ],
        ),
    ]
