# Generated by Django 4.0.4 on 2023-01-27 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclevmainmodel',
            old_name='descriptionut',
            new_name='description',
        ),
    ]
