# Generated by Django 4.0.4 on 2023-01-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productPMainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=200)),
                ('unique_code', models.CharField(max_length=100, unique=True)),
                ('price', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
