# Generated by Django 4.0.4 on 2023-01-18 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0008_alter_accountusercartproduct_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderOMainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], max_length=120)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderOMainModel_owner', to='account.accountusermodel')),
                ('product', models.ManyToManyField(related_name='orderOMainModel_product', to='account.accountusercartproduct')),
            ],
        ),
    ]
