# Generated by Django 4.0.4 on 2023-01-06 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_customer', models.BooleanField()),
                ('is_admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='accountUserProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('date_of_birth', models.DateField()),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.accountusermodel')),
            ],
        ),
        migrations.CreateModel(
            name='accountUserCartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.PositiveIntegerField(blank=True, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.accountusermodel')),
                ('products', models.ManyToManyField(to='product.productpmainmodel')),
            ],
        ),
    ]
