# Generated by Django 4.0.4 on 2023-01-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountusermodel',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountusermodel',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
