# Generated by Django 4.0.4 on 2023-01-07 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_accountusermodel_is_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountUserLoginOtpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('active', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accountusermodel')),
            ],
        ),
    ]
