# Generated by Django 4.0.4 on 2023-01-07 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productpimagemodel'),
        ('account', '0003_accountuserloginotpmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountusercartmodel',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accountUserCartModel_owner', to='account.accountusermodel'),
        ),
        migrations.AlterField(
            model_name='accountusercartmodel',
            name='products',
            field=models.ManyToManyField(related_name='accountUserCartModel_product', to='product.productpmainmodel'),
        ),
        migrations.AlterField(
            model_name='accountuserloginotpmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountUserLoginOtpModel_owner', to='account.accountusermodel'),
        ),
    ]
