# Generated by Django 4.0.4 on 2023-01-10 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productpimagemodel_product'),
        ('account', '0005_alter_accountusercartmodel_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='accoutUserCartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], max_length=120)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accoutUserCartProduct_owner', to='account.accountusermodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accoutUserCartProduct_product', to='product.productpmainmodel')),
            ],
        ),
        migrations.AlterField(
            model_name='accountusercartmodel',
            name='products',
            field=models.ManyToManyField(related_name='accountUserCartModel_products', to='account.accoutusercartproduct'),
        ),
    ]
