# Generated by Django 4.0.4 on 2023-01-18 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productpimagemodel_product'),
        ('account', '0007_rename_accoutusercartproduct_accountusercartproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountusercartproduct',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountUserCartProduct_owner', to='account.accountusermodel'),
        ),
        migrations.AlterField(
            model_name='accountusercartproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountUserCartProduct_product', to='product.productpmainmodel'),
        ),
    ]
