# Generated by Django 4.0.4 on 2023-01-27 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsusermodel',
            old_name='phone',
            new_name='phonenumber',
        ),
    ]
